name: git-pr-release

on:
  push:
    branches: [ "main" ]

jobs:
  create-release-pull-request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: create release pr
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        GIT_PR_RELEASE_BRANCH_STAGING: main
        GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
      run: |
        gem install git-pr-release
        git-pr-release
